




.build/uno/src/arduino/arduino.cpp : src/arduino/arduino.ino
	@mkdir -p .build/uno/src/arduino
	@echo [93msrc/arduino/arduino.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/uno/src/arduino/arduino.cpp
	@true

